import { readFileSync } from 'node:fs';
import type { CapacitorConfig } from '@capacitor/cli';

/**
 * The Android app is a native shell around the live site. The site's address
 * lives in capacitor.app.json (also read by android/app/build.gradle and
 * scripts/prepare-capacitor.mjs). Override locally with
 * CAP_SERVER_URL=http://<your-LAN-ip>:3000.
 */
const { appUrl, startPath } = JSON.parse(readFileSync('capacitor.app.json', 'utf8')) as {
  appUrl: string;
  startPath: string;
};
const base = (process.env.CAP_SERVER_URL ?? appUrl).replace(/\/+$/, '');

const config: CapacitorConfig = {
  appId: 'com.soylai.forms',
  appName: 'SOYL Forms',
  // Generated by scripts/prepare-capacitor.mjs; holds the offline screen.
  webDir: 'capacitor-www',
  // Lets the site recognise the app (lib/native.ts) to hide in-app purchases.
  appendUserAgent: 'SOYLFormsApp',
  server: {
    url: `${base}${startPath}`,
    // Shown when the site can't be reached (offline, DNS, server down).
    errorPath: 'error.html',
    // Keep the whole site in-app; other domains open in the browser.
    allowNavigation: [new URL(base).host],
    cleartext: base.startsWith('http://'),
  },
  android: {
    allowMixedContent: false,
    captureInput: true,
    webContentsDebuggingEnabled: false,
  },
};

export default config;
